# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push]

repos:
    # local hooks
    - repo: local
      hooks:
        - id: ruff-format
          name: ruff format
          entry: uv run ruff format --exit-non-zero-on-format
          language: system
          types_or: [python, jupyter]
        - id: ruff-check
          name: ruff check
          entry: uv run ruff check --fix --show-fixes --exit-non-zero-on-fix
          language: system
          types_or: [python, jupyter]
        - id: mypy
          name: mypy
          entry: uv run mypy
          language: system
          types: [python]
          require_serial: true

    # "official" pre-commit hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-executables-have-shebangs
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: check-symlinks

    # third-party hooks
    - repo: https://github.com/kynan/nbstripout
      rev: 0.9.1
      hooks:
          - id: nbstripout
